import mongoose from "mongoose";
import { MongoMemoryServer } from "mongodb-memory-server";

let mongoServer = null;

async function connectDB() {
  // If already connected, don't connect again
  if (mongoose.connection.readyState === 1) {
    return mongoose.connection;
  }

  // Start the in-memory MongoDB server
  if (!mongoServer) {
    mongoServer = await MongoMemoryServer.create();
  }

  // Get the URI (like 'mongodb://localhost:27017/library' from your lab,
  // but auto-generated by the memory server)
  const uri = mongoServer.getUri();

  // Connect mongoose to the in-memory server
  await mongoose.connect(uri);
  console.log("MongoDB connected:", uri);

  return mongoose.connection;
}

export default connectDB;
